version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: barbearia_db
    restart: always
    environment:
      POSTGRES_USER: barberadmin
      POSTGRES_PASSWORD: B4rb3rPr3m1um!2026
      POSTGRES_DB: barbearia_premium
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
